kind: Deployment 
apiVersion: apps/v1
metadata:
  name: lenomdemondep
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hostname
      version: v101
  template:
    metadata:
      labels:
        app: hostname
        version: v101
    spec:
      containers:
        - name: nginx-hostname
          image: nginx:1.18.0
          ports:
            - containerPort: 80
      containers:
        - name: simple-webapp-color
          image: mmumshad/simple-webapp-color
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: pink
