apiVersion: v1
kind: Pod
metadata:
  name: mes-couilles-sur-ton-nez
spec:
  containers:
    - name: simple-webapp-color
      image: mmumshad/simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: red
