apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
      
# k get all -n production 
#k describe -n production service service-nodeport-web 

#Name:                     service-nodeport-web
#Namespace:                production
#Labels:                   <none>
#Annotations:              Selector:  app=web
#Type:                     NodePort
#IP:                       10.110.215.38
#Port:                     <unset>  8080/TCP
#TargetPort:               8080/TCP
#NodePort:                 <unset>  30008/TCP
#Endpoints:                10.244.0.6:8080,10.244.0.7:8080
#Session Affinity:         None
#External Traffic Policy:  Cluster
#Events:                   <none>
