apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_USER
        value: eazy
  volumes:
  - name: mysql-data
